[package]
name = "wzCore"
version = "0.1.0"
edition = "2018"
authors = ["wangwutao<wawuta@126.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"